"""Add saved recommendations table

Revision ID: 380949f67950
Revises: c8cb303baf16
Create Date: 2026-07-07 22:05:21.715484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380949f67950'
down_revision = 'c8cb303baf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_plan', sa.JSON(), nullable=False),
    sa.Column('diet_plan', sa.JSON(), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fats_g', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_recommendations')
    # ### end Alembic commands ###
