"""Add fitness profile table

Revision ID: 39ef47d02a12
Revises: f6966730b290
Create Date: 2026-07-07 21:19:26.950201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39ef47d02a12'
down_revision = 'f6966730b290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('Male', 'Female', 'Other', name='gender_enum'),
               existing_nullable=False)
        batch_op.alter_column('goal',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('Lose Weight', 'Gain Weight', 'Maintain Weight', name='goal_enum'),
               existing_nullable=False)
        batch_op.alter_column('activity_level',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('Sedentary', 'Lightly Active', 'Moderately Active', 'Very Active', 'Extremely Active', name='activity_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.alter_column('activity_level',
               existing_type=sa.Enum('Sedentary', 'Lightly Active', 'Moderately Active', 'Very Active', 'Extremely Active', name='activity_enum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('goal',
               existing_type=sa.Enum('Lose Weight', 'Gain Weight', 'Maintain Weight', name='goal_enum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.Enum('Male', 'Female', 'Other', name='gender_enum'),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
