"""Add workout hours, sleep hours and daily steps

Revision ID: 4d33f66af7a3
Revises: 9eb307bd60c3
Create Date: 2026-07-10 23:22:43.537502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d33f66af7a3'
down_revision = '9eb307bd60c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_hours', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sleep_hours', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('daily_steps', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.drop_column('daily_steps')
        batch_op.drop_column('sleep_hours')
        batch_op.drop_column('workout_hours')

    # ### end Alembic commands ###
