"""Add fitness profile table

Revision ID: 66a6d102afbc
Revises: 39ef47d02a12
Create Date: 2026-07-07 21:38:01.690448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66a6d102afbc'
down_revision = '39ef47d02a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_weight_kg', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('body_fat_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('water_intake_liters', sa.Float(), nullable=True))
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('Male', 'Female', 'Other'),
               type_=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'),
               existing_nullable=False)
        batch_op.alter_column('goal',
               existing_type=mysql.ENUM('Lose Weight', 'Gain Weight', 'Maintain Weight'),
               type_=sa.Enum('LOSE_WEIGHT', 'GAIN_WEIGHT', 'MAINTAIN_WEIGHT', name='fitnessgoal'),
               existing_nullable=False)
        batch_op.alter_column('activity_level',
               existing_type=mysql.ENUM('Sedentary', 'Lightly Active', 'Moderately Active', 'Very Active', 'Extremely Active'),
               type_=sa.Enum('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', 'EXTREMELY_ACTIVE', name='activitylevel'),
               existing_nullable=False)
        batch_op.drop_column('bmi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmi', mysql.FLOAT(), nullable=True))
        batch_op.alter_column('activity_level',
               existing_type=sa.Enum('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', 'EXTREMELY_ACTIVE', name='activitylevel'),
               type_=mysql.ENUM('Sedentary', 'Lightly Active', 'Moderately Active', 'Very Active', 'Extremely Active'),
               existing_nullable=False)
        batch_op.alter_column('goal',
               existing_type=sa.Enum('LOSE_WEIGHT', 'GAIN_WEIGHT', 'MAINTAIN_WEIGHT', name='fitnessgoal'),
               type_=mysql.ENUM('Lose Weight', 'Gain Weight', 'Maintain Weight'),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'),
               type_=mysql.ENUM('Male', 'Female', 'Other'),
               existing_nullable=False)
        batch_op.drop_column('water_intake_liters')
        batch_op.drop_column('body_fat_percentage')
        batch_op.drop_column('target_weight_kg')

    # ### end Alembic commands ###
