"""Add dietary preference to fitness profile

Revision ID: fdd28666d961
Revises: 4d33f66af7a3
Create Date: 2026-07-10 23:42:22.644693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd28666d961'
down_revision = '4d33f66af7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dietary_preference', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.drop_column('dietary_preference')

    # ### end Alembic commands ###
